#!/usr/bin/perl -w
#===================================================================================
#
#         FILE:  |FILENAME|
#
#        USAGE:  ./|FILENAME| 
#
#     SYNOPSIS:  |CURSOR|
#
#  DESCRIPTION:  
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  |AUTHOR| (|AUTHORREF|), |EMAIL|
#      COMPANY:  |COMPANY|
#      VERSION:  1.0
#      CREATED:  |DATE|
#     REVISION:  ---
#===================================================================================

use strict;


